### ISSUE TITLE
Please bump versions more frequently

### ISSUE THREAD

**Issue by seiyria** [lordnull/dice.js#17]
As it stands, I currently cannot (sensibly) use dice.js on npm with the latest issue I requested because the only available install targets are 0.8.0. Right now, to get dice.js, I have to `npm install git+https://github.com/lordnull/dice.js.git#21124f7bf18224b774d0cb6e82ef3872a534a98e`

What I normally will do is have a script where it updates all of my package metadata (package/bower.json) and then pushes to the respective places. After every change is made there is a patch bump, unless it's minor-worthy or major-worthy, just so people can install at whatever point in time they want without having to specify commits (since most package managers work a lot better with tags).

Thanks again for the great lib!

**Comment by lordnull** [comment]
Meant to do this as soon as the latest couple of features were resolved :). Npm (and bower if anyone is using it) are all up to date with 0.9.0. Maybe I'll reach a 1.0 release!

All of the [tags](https://github.com/lordnull/dice.js/tags) so far have been at minor level since there have only been feature additions with no backwards incompatible changes (and no bugs have ever been fixed!)

**Comment by seiyria** [comment]
Right on! I gotta say, you do very well with this, no surprise there's no bugs! :P Thanks again for addressing this!
