### ISSUE TITLE
Fate/Fudge dice support

### ISSUE THREAD

**Issue by tritium21** [lordnull/dice.js#19]
It would be handy to have support for fate/fudge dice.

Fudge dice (same as Fate dice) are d6 with 2 faces with a `+`, 2 faces with a `-`, and 2 blank faces.  They are typically rolled in counts of 4.  A `+` adds 1 to the total rolled, a `-` subtracts 1, and blank faces do nothing to to total.

Syntactically, something like `4df+1` would be the preferred syntax.

**Comment by lordnull** [comment]
As someone who has just starting running a fate campaign, I agree. While it can be done by adding syntax, a fate die is essentially a 3 sided die, just numbered -1, 0, 1, rather than the usual 1, 2, 3. So if the syntax allowed a negative minimum, it would work (albeit a bit more verbose). So a fate die roll would be represented by:

    4d-1..1 + [Relevant Skill]

This means it would also support weirder dice/rolls, like this one that says the minimum is -12 and the maximum is -2:

    3w-12..-2 + [Fantastic Legumes]

In sort, allow min and max to be negative.

**Comment by lordnull** [comment]
So, as shown in the tests written (and playing with it in the console), this was already supported. So, I've committed the created tests and updated the docs.

Mathematically this all works out because a fate die has 2 of each face, meaning a 1/3 chance of any particular result, which is the same as the "-1..1" syntax.
