### ISSUE TITLE
Can you explain the ".." syntax further in the readme?

### ISSUE THREAD

**Issue by seiyria** [lordnull/dice.js#24]
I _think_ I get it: if the number is below the right side of the die, then it becomes the min. if it's above, it becomes the max.

so if we have: 
* 1d6..3 - it becomes 1d6, reroll 1, 2 (since 3 is now the min)
* 1d6..10 - it becomes 1d6 + 4 (since 10 is now the max)

It becomes really tricky to understand when you have negative numbers in there, I think. and I don't know why 3d2..0 works, either.

Could these kinds of examples be added with explanations? Thanks!

**Comment by lordnull** [comment]
It's a bit more subtle than one side being a min and the other side being a max. While the code has them labeled as such, in reality it just designates a range of values, even a range of exactly one value.

For any given `n..m` expression there is only one roll actually done, and that roll is taken from Math.random(). So let's take a look at some expressions and suppose that Math.random() gave us 0.0, 0.25, 0.5, 0.75, and 1.0.

Roll | 0.0 | 0.25 | 0.5 | 0.75 | 1.0
-|-|-|-|-|-
3..7 | 3 | 4 | 5 | 6 | 7
7..3 | 7 | 6 | 5 | 4 | 3
-3..-7 | -7 | -6 | -5 | -4 | -3
-7..-3 | -3 | -4 | -5 | -6 | -7

So we see we get the set of values with the pair of `3..7` and `7..3`; and the same set of values for the pair of `-3..-7` and `-7..-3`. This is because `3..7` and `7..3` represent the same range of values, anywhere between 7 and 3.

This is also why ranges such as `-1..1`, `2..0`, and `0..-12` work. They are all simply expressions of different ranges.

Things get a bit trickier when we introduce the `xwy` syntax. `1d3..6` is the same as saying `3..6`, which we know is the same as saying `6..3`. This is because in all three cases we are doing exactly one roll. However, `1w3..6` does not mean the same thing as `1w6..3`.

The `w` indicates that any roll returns the maximum possible result, roll again again and add that result to the sum (commonly called exploding dice). It doesn't look at the highest number in the `..` syntax, instead it looks at the right-most value, what we have been calling `max`. So, in the case of `1w3..6`, the roll is exploded on a 6. In the case of `1w6..3`, the roll is exploded on a 3.

I'll see if I can condense this to something more digestible and put it into the readme.

**Comment by seiyria** [comment]
I see, this is interesting. So what I've been doing for my game is that:

* Every class rolls `xdy` dice for damage.
* Thieves and warriors have a "boost" to their min damage, say 25%, so they roll `xdy..[x/4]`. What I think this means is that they just have the min value, instead of being 1, be `x/4`. So, if my weapon rolled `3d12`, warriors would instead roll `3d12..3` to roll at least 3 damage for each roll. 

So what I'm doing at a basic level is correct, but my understanding was flawed. I have read about the W dice and they're pretty interesting, but not wholly applicable to me (yet). 

Thanks for the explanation.

**Comment by Praxiteles** [comment]
We are looking to use this implementation for a 3D Virtual Table Top (https://github.com/RobRendell/gTove)

One great help would be adding the answers like you have done above to the explanations on the main documentation page. 

That would allow us to refer users to your page.

**Comment by lordnull** [comment]
I've updated the readme. It may be a good idea for me to break up the readme into wiki pages, one oriented toward developers, and another toward...non-developers.
